### ISSUE TITLE
Bars aren't to scale

### ISSUE THREAD

**Issue by RollingStar** [opencleveland/refundcleveland#96]
The bars aren't to scale. This makes it hard to build an intuition about how much bigger one budget is over another.

![image](https://user-images.githubusercontent.com/4810902/108084041-c0841980-7041-11eb-8253-011bf7abdedd.png)

This image implies that 50% is approximately 15%.

![image](https://user-images.githubusercontent.com/4810902/108084142-db568e00-7041-11eb-994c-bb1a6a36cf6f.png)

Potential further reading: https://infovis-wiki.net/wiki/Lie_Factor

**Comment by jessicalynch** [comment]
Yeah, this is something we have to solve- thank you for raising the issue. The bars are using the same scale, but there is an extra padding on the bottom of each bar so that there is something to grab when the bar is at 0%.

We could adjust the script so that a drag event on the light grey background bar would increase the bar height. We could also add, as @austindavis suggested, a tap event handler, where the user could tap the bar and type in their desired percentage.
